### ISSUE TITLE
[Bug?] Teleportation occurs when allays are tied to a fence post

### ISSUE THREAD

**Issue by BlueJayofEvil** [Estecka/mc-Allay-Behave#3]
I'm not sure if this is a bug or an oversight, but the teleportation feature activates when allays are tied to a fence post using a lead and trying to follow a player. Allays try to reach me while tied up and after the range threshold is reached, they teleport to me and drop their leads where they appear.
Maybe adding being tied with a lead as another condition of disabling the teleport function would fix this?

**Comment by Estecka** [comment]
Fixed in v1.3.1.
